### ISSUE TITLE
LibraryBase.cs: SendToAll() breaks SubscribeToAll() when using same event

### ISSUE THREAD

**Issue by darwinrecreant** [lindenlab/sansar-script#3]
When sending the same event as being subscribed to, within same script, the subscription does not fire, including subsequent events from other scripts.

## Steps to reproduce:
1) Create a scene from base template
2) Add the following script to the scene:
```csharp
using Sansar.Script;
using ScriptLibrary;

public class SimpleEventTest : SceneObjectBase {
  protected override void SimpleInit() {
    SubscribeToAll("test", (ScriptEventData ev) => {
      Log.Write("OK");
    });
    SendToAll("test", null);
  }
}
```
3) Visit scene
4) The "OK" message does not appear in log

## Workaround/Possible clue:
Adding a comma to the event subscription fixes the issue
```csharp
using Sansar.Script;
using ScriptLibrary;

public class SimpleEventTest : SceneObjectBase {
  protected override void SimpleInit() {
    SubscribeToAll("test,", (ScriptEventData ev) => {
      Log.Write("OK");
    });
    SendToAll("test", null);
  }
}
```

**Comment by leslie-linden** [comment]
@kelly-linden will probably want to investigate this a bit more carefully.  thanks for letting us know!

**Comment by BinahLinden** [comment]
Has this issue been satisfied?

**Comment by darwinrecreant** [comment]
It has! works good.
